CXX = g++

SOURCES = $(wildcard *.cpp)
# main.cpp SquareEquationSolve.cpp test.cpp interface.cpp
OBJECTS = $(patsubts %.cpp, %.o, $(SOURCES))
APPLICATION = Square

all: $(APPLICATION)

$(APPLICATION): $(SOURCES)
	$(CXX) $(OBJECTS) -o $@
%.o: %.cpp:
	$(CXX) -c $< -o $@
