CXXFLAGS = -с
CXX = g++

SOURCES = $(wildcard *.cpp)
# main.cpp SquareEquationSolve.cpp test.cpp interface.cpp
OBJECTS = $(patsubts %.cpp, %.o, $(SOURCES))
APPLICATION = Square

all: $(APPLICATION)

$(APPLICATION): $(SOURCES)
	$(CXX) $(OBJECTS) -o $@

# $^ - all dependencies $< - first dep $@ - target

%.o: %.cpp:
	$(CXX) $(CXXFLAGS) $< -o $@
